package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", catalog = "ecomerce")
public class Contacto implements java.io.Serializable {

	private Integer idcontacto;
	private String nombre;
	private String email;
	private String asunto;
	private String mensaje;

	public Contacto() {
	}

	public Contacto(String nombre) {
		this.nombre = nombre;
	}

	public Contacto(String nombre, String email, String asunto, String mensaje) {
		this.nombre = nombre;
		this.email = email;
		this.asunto = asunto;
		this.mensaje = mensaje;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcontacto", unique = true, nullable = false)
	public Integer getIdcontacto() {
		return this.idcontacto;
	}

	public void setIdcontacto(Integer idcontacto) {
		this.idcontacto = idcontacto;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "asunto", length = 100)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "mensaje", length = 500)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
