package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", catalog = "ecomerce")
public class Factura implements java.io.Serializable {

	private Integer idfactura;
	private String facturacol;

	public Factura() {
	}

	public Factura(String facturacol) {
		this.facturacol = facturacol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfactura", unique = true, nullable = false)
	public Integer getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(Integer idfactura) {
		this.idfactura = idfactura;
	}

	@Column(name = "facturacol", nullable = false, length = 45)
	public String getFacturacol() {
		return this.facturacol;
	}

	public void setFacturacol(String facturacol) {
		this.facturacol = facturacol;
	}

}
