package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "ecomerce")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private Categoria categoria;
	private Empresa empresa;
	private String nombre;
	private BigDecimal precio;
	private int cantidad;
	private String descripcion;
	private String urlimg;
	private Integer idusuario;
	private Integer idestado;
	private Date fecharegistro;
	private Set<Reservadetalle> reservadetalles = new HashSet<Reservadetalle>(0);

	public Producto() {
	}

	public Producto(String nombre, BigDecimal precio, int cantidad) {
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
	}

	public Producto(Categoria categoria, Empresa empresa, String nombre, BigDecimal precio, int cantidad,
			String descripcion, String urlimg, Integer idusuario, Integer idestado, Date fecharegistro,
			Set<Reservadetalle> reservadetalles) {
		this.categoria = categoria;
		this.empresa = empresa;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.urlimg = urlimg;
		this.idusuario = idusuario;
		this.idestado = idestado;
		this.fecharegistro = fecharegistro;
		this.reservadetalles = reservadetalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false, precision = 18)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "urlimg", length = 500)
	public String getUrlimg() {
		return this.urlimg;
	}

	public void setUrlimg(String urlimg) {
		this.urlimg = urlimg;
	}

	@Column(name = "idusuario")
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idestado")
	public Integer getIdestado() {
		return this.idestado;
	}

	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", length = 19)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Reservadetalle> getReservadetalles() {
		return this.reservadetalles;
	}

	public void setReservadetalles(Set<Reservadetalle> reservadetalles) {
		this.reservadetalles = reservadetalles;
	}

}
