package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reservadetalle generated by hbm2java
 */
@Entity
@Table(name = "reservadetalle", catalog = "ecomerce")
public class Reservadetalle implements java.io.Serializable {

	private Integer idreservadetalle;
	private Producto producto;
	private Reserva reserva;
	private String nombre;
	private String fechareserva;
	private int cantidad;
	private BigDecimal precio;
	private BigDecimal descuento;

	public Reservadetalle() {
	}

	public Reservadetalle(Producto producto, Reserva reserva, String nombre, String fechareserva, int cantidad,
			BigDecimal precio) {
		this.producto = producto;
		this.reserva = reserva;
		this.nombre = nombre;
		this.fechareserva = fechareserva;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	public Reservadetalle(Producto producto, Reserva reserva, String nombre, String fechareserva, int cantidad,
			BigDecimal precio, BigDecimal descuento) {
		this.producto = producto;
		this.reserva = reserva;
		this.nombre = nombre;
		this.fechareserva = fechareserva;
		this.cantidad = cantidad;
		this.precio = precio;
		this.descuento = descuento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idreservadetalle", unique = true, nullable = false)
	public Integer getIdreservadetalle() {
		return this.idreservadetalle;
	}

	public void setIdreservadetalle(Integer idreservadetalle) {
		this.idreservadetalle = idreservadetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idreserva", nullable = false)
	public Reserva getReserva() {
		return this.reserva;
	}

	public void setReserva(Reserva reserva) {
		this.reserva = reserva;
	}

	@Column(name = "nombre", nullable = false, length = 300)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "fechareserva", nullable = false, length = 10)
	public String getFechareserva() {
		return this.fechareserva;
	}

	public void setFechareserva(String fechareserva) {
		this.fechareserva = fechareserva;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", nullable = false, precision = 18)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "descuento", precision = 18)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

}
