package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", catalog = "ecomerce")
public class Reserva implements java.io.Serializable {

	private Integer idreserva;
	private Usuario usuario;
	private int cantidad;
	private BigDecimal subtotal;
	private BigDecimal descuento;
	private BigDecimal total;
	private Date fecharegistro;
	private Character estadopago;
	private int estado;
	private Set<Reservadetalle> reservadetalles = new HashSet<Reservadetalle>(0);

	public Reserva() {
	}

	public Reserva(Usuario usuario, int cantidad, BigDecimal subtotal, BigDecimal total, int estado) {
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
		this.total = total;
		this.estado = estado;
	}

	public Reserva(Usuario usuario, int cantidad, BigDecimal subtotal, BigDecimal descuento, BigDecimal total,
			Date fecharegistro, Character estadopago, int estado, Set<Reservadetalle> reservadetalles) {
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
		this.descuento = descuento;
		this.total = total;
		this.fecharegistro = fecharegistro;
		this.estadopago = estadopago;
		this.estado = estado;
		this.reservadetalles = reservadetalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idreserva", unique = true, nullable = false)
	public Integer getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(Integer idreserva) {
		this.idreserva = idreserva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "subtotal", nullable = false, precision = 10, scale = 3)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "descuento", precision = 10, scale = 3)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "total", nullable = false, precision = 10, scale = 3)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", length = 19)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "estadopago", length = 1)
	public Character getEstadopago() {
		return this.estadopago;
	}

	public void setEstadopago(Character estadopago) {
		this.estadopago = estadopago;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reserva")
	public Set<Reservadetalle> getReservadetalles() {
		return this.reservadetalles;
	}

	public void setReservadetalles(Set<Reservadetalle> reservadetalles) {
		this.reservadetalles = reservadetalles;
	}

}
