package edu.pe.shop.entity;
// Generated 26-jul-2018 18:59:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "ecomerce")
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String usuario;
	private String password;
	private String nombre;
	private String apellido;
	private String telefono;
	private String direccion;
	private String direcciond;
	private String ciudad;
	private String codigoPostal;
	private String pais;
	private String region;
	private String facnombre;
	private String facapellido;
	private String factelefono;
	private String facdireccion;
	private String facdirecciond;
	private String facciudad;
	private String faccodPostal;
	private String facpais;
	private String facregion;
	private Date fecharegistro;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Usuario() {
	}

	public Usuario(String usuario, String password, String nombre, String apellido) {
		this.usuario = usuario;
		this.password = password;
		this.nombre = nombre;
		this.apellido = apellido;
	}

	public Usuario(String usuario, String password, String nombre, String apellido, String telefono, String direccion,
			String direcciond, String ciudad, String codigoPostal, String pais, String region, String facnombre,
			String facapellido, String factelefono, String facdireccion, String facdirecciond, String facciudad,
			String faccodPostal, String facpais, String facregion, Date fecharegistro, Set<Reserva> reservas) {
		this.usuario = usuario;
		this.password = password;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.direccion = direccion;
		this.direcciond = direcciond;
		this.ciudad = ciudad;
		this.codigoPostal = codigoPostal;
		this.pais = pais;
		this.region = region;
		this.facnombre = facnombre;
		this.facapellido = facapellido;
		this.factelefono = factelefono;
		this.facdireccion = facdireccion;
		this.facdirecciond = facdirecciond;
		this.facciudad = facciudad;
		this.faccodPostal = faccodPostal;
		this.facpais = facpais;
		this.facregion = facregion;
		this.fecharegistro = fecharegistro;
		this.reservas = reservas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuario", unique = true, nullable = false)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 100)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "direcciond", length = 200)
	public String getDirecciond() {
		return this.direcciond;
	}

	public void setDirecciond(String direcciond) {
		this.direcciond = direcciond;
	}

	@Column(name = "ciudad", length = 100)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "codigo_postal", length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "pais", length = 100)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "region", length = 100)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "facnombre", length = 100)
	public String getFacnombre() {
		return this.facnombre;
	}

	public void setFacnombre(String facnombre) {
		this.facnombre = facnombre;
	}

	@Column(name = "facapellido", length = 100)
	public String getFacapellido() {
		return this.facapellido;
	}

	public void setFacapellido(String facapellido) {
		this.facapellido = facapellido;
	}

	@Column(name = "factelefono", length = 15)
	public String getFactelefono() {
		return this.factelefono;
	}

	public void setFactelefono(String factelefono) {
		this.factelefono = factelefono;
	}

	@Column(name = "facdireccion", length = 200)
	public String getFacdireccion() {
		return this.facdireccion;
	}

	public void setFacdireccion(String facdireccion) {
		this.facdireccion = facdireccion;
	}

	@Column(name = "facdirecciond", length = 200)
	public String getFacdirecciond() {
		return this.facdirecciond;
	}

	public void setFacdirecciond(String facdirecciond) {
		this.facdirecciond = facdirecciond;
	}

	@Column(name = "facciudad", length = 100)
	public String getFacciudad() {
		return this.facciudad;
	}

	public void setFacciudad(String facciudad) {
		this.facciudad = facciudad;
	}

	@Column(name = "faccod_postal", length = 10)
	public String getFaccodPostal() {
		return this.faccodPostal;
	}

	public void setFaccodPostal(String faccodPostal) {
		this.faccodPostal = faccodPostal;
	}

	@Column(name = "facpais", length = 100)
	public String getFacpais() {
		return this.facpais;
	}

	public void setFacpais(String facpais) {
		this.facpais = facpais;
	}

	@Column(name = "facregion", length = 100)
	public String getFacregion() {
		return this.facregion;
	}

	public void setFacregion(String facregion) {
		this.facregion = facregion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", length = 19)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
